  <div class="box" style="margin-bottom: 0px; margin-left: auto; margin-right: auto; margin-top: 0px; width: 99%;">
   <div class="cornerImage tl">&nbsp;</div><div class="cornerImage tr">&nbsp;</div>
   <div class="content" style="padding: 0px;">
    <table style="width: 100%" cellpadding="0" cellspacing="0">
     <tr>
      <td><a href="index.php">Home</a></td>
      <td><a href="member.php">My Rides</a></td>
      <td><a href="member_prefs.php">My Profile</a></td>
      <td><a href="new_route.php">New Ride</a></td>
      <td><a href="about.php">About</a></td>
      <td><a href="logout.php">Logout</a></td>
     </tr>
    </table>
   </div>
   <div class="cornerImage bl">&nbsp;</div><div class="cornerImage br">&nbsp;</div>
   <div class="fineprint">&nbsp;</div>
  </div>
